<?php



/**
 * Bootstrap for PhpSpreadsheet classes.
 */

// This sucks, but we have to try to find the composer autoloader

$vendorDirPath = realpath($_SERVER["DOCUMENT_ROOT"] . '/vendor');

// var_dump($vendorDirPath);
// exit;

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Helper;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}


// Create new Spreadsheet object
$objPHPExcel = new Spreadsheet();

// Set document properties
$objPHPExcel->getProperties()->setCreator("Desarrollos .csv")
                             ->setLastModifiedBy("Desarrollos .csv")
                             ->setTitle("Office 2007 XLSX Test Document")
                             ->setSubject("Office 2007 XLSX Test Document")
                             ->setDescription("Listado Alumnos Jornada.")
                             ->setKeywords("office 2007 openxml php")
                             ->setCategory("Test result file");

// 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:L1');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Verdana');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(17);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(18);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('AL1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(19);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(20);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:L1')
            ->setCellValue('A1', strtoupper($PruebasInformeProfesor['nombre_titulo']));
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('AL1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
                            
 
$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
); 

$objPHPExcel->getActiveSheet()->getStyle('A1:L1')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A2:L2')
            ->setCellValue('A2', 'Prueba  '.strtoupper($PruebasInformeProfesor['nombre_prueba']));
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A2:L2')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A2:L2')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A2:L2')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A2:L2')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A2:L2')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('A2:L2')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'italic' => true,
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$arreglo_estilo_letras = array(

    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => 'FFFFFF'),
        'size'  => 12,
        'name'  => 'Calibri'
    )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A3:A3')
            ->setCellValue('A3', 'N° de Pregunta');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B3:B3')
            ->setCellValue('B3', 'Alternativa Correcta');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C3:C3')
            ->setCellValue('C3', '% ALT-A');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D3:D3')
            ->setCellValue('D3', '% ALT-B');
$objPHPExcel->getActiveSheet()->getStyle('D3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D3')->applyFromArray($arreglo_estilo_letras);
 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('E3:E3')
            ->setCellValue('E3', '% ALT-C');
$objPHPExcel->getActiveSheet()->getStyle('E3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('E3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('F3:F3')
            ->setCellValue('F3', '% ALT-D');
$objPHPExcel->getActiveSheet()->getStyle('F3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('F3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('G3:G3')
            ->setCellValue('G3', '% ALT-E');
$objPHPExcel->getActiveSheet()->getStyle('G3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('G')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('G3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('G3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('G3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('G3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('G3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('G3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('H3:H3')
            ->setCellValue('H3', '% Buenas');
$objPHPExcel->getActiveSheet()->getStyle('H3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('H')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('H3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('H3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('H3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('H3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('H3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('H3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('I3:I3')
            ->setCellValue('I3', '% Malas');
$objPHPExcel->getActiveSheet()->getStyle('I3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('I')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('I3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('I3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('I3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('I3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('I3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('I3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('J3:J3')
            ->setCellValue('J3', '% Omitidas');
$objPHPExcel->getActiveSheet()->getStyle('J3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('J')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('J3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('J3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('J3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('J3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('J3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('J3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('K3:K3')
            ->setCellValue('K3', 'Nivel Discrim.');
$objPHPExcel->getActiveSheet()->getStyle('K3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('K')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('K3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('K3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('K3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('K3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('K3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('K3')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('L3:L3')
            ->setCellValue('L3', 'Nivel Dificultad.');
$objPHPExcel->getActiveSheet()->getStyle('L3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('L')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('L3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('L3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('L3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('L3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('L3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('L3')->applyFromArray($arreglo_estilo_letras);



$objPHPExcel->getActiveSheet()->getStyle('A3:L3')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A3:L3')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A3:L3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A3:L3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
 


 




$objPHPExcel->getActiveSheet()->setTitle(substr(preg_replace('([^A-Za-z0-9])', ' ', $PruebasInformeProfesor["nombre_titulo"]), 0, 30));

$i_indice = 4;



foreach ($PruebasInformeProfesor["PruebaPauta"] as $key => $value) {





    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('A' . $i_indice . ':A' . $i_indice)
    ->setCellValue('A' . $i_indice, $value['numero_pregunta']);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('B' . $i_indice . ':B' . $i_indice)
        ->setCellValue('B' . $i_indice, $value['correcta']);
    $objPHPExcel->getActiveSheet()->getStyle('B' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('B' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('C' . $i_indice . ':C' . $i_indice)
        ->setCellValue('C' . $i_indice, $value['alternativa_a']);
    $objPHPExcel->getActiveSheet()->getStyle('C' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('C' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    if($value['alternativa_a_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('C' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('C' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_a_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('C' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }


    
    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('D' . $i_indice . ':D' . $i_indice)
        ->setCellValue('D' . $i_indice, $value['alternativa_b']);
    $objPHPExcel->getActiveSheet()->getStyle('D' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('D' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    if($value['alternativa_b_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('D' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('D' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_b_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('D' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }


    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('E' . $i_indice . ':E' . $i_indice)
            ->setCellValue('E' . $i_indice, $value['alternativa_c']);
    $objPHPExcel->getActiveSheet()->getStyle('E' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('E' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    if($value['alternativa_c_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('E' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('E' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_c_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('E' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }



    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('F' . $i_indice . ':F' . $i_indice)
            ->setCellValue('F' . $i_indice, $value['alternativa_d']);
    $objPHPExcel->getActiveSheet()->getStyle('F' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('F' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    if($value['alternativa_d_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('F' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('F' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_d_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('F' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }



    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('G' . $i_indice . ':G' . $i_indice)
            ->setCellValue('G' . $i_indice, $value['alternativa_e']);
    $objPHPExcel->getActiveSheet()->getStyle('G' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('G' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    if($value['alternativa_e_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('G' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('G' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_e_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('G' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }



    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('H' . $i_indice . ':H' . $i_indice)
                ->setCellValue('H' . $i_indice, $value['alternativa_buenas']);
    $objPHPExcel->getActiveSheet()->getStyle('H' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('H' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('I' . $i_indice . ':I' . $i_indice)
                ->setCellValue('I' . $i_indice, $value['alternativa_malas']);
    $objPHPExcel->getActiveSheet()->getStyle('I' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('I' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    if($value['alternativa_malas_color'] != ""){

        $objPHPExcel->getActiveSheet()->getStyle('I' . $i_indice)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('I' . $i_indice)->getFill()->getStartColor()->setRGB($value['alternativa_malas_color']);
    
        $objPHPExcel->getActiveSheet()->getStyle('I' . $i_indice)->getBorders()->applyFromArray(
            array(
                'left'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'right'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'top'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
                'button'     => array(
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array(
                        'rgb' => '58FF33'
                    )
                ),
       
            )
        );

    }



    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('J' . $i_indice . ':J' . $i_indice)
                ->setCellValue('J' . $i_indice, $value['alternativa_omitidas']);
    $objPHPExcel->getActiveSheet()->getStyle('J' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('J' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        
    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('K' . $i_indice . ':K' . $i_indice)
                    ->setCellValue('K' . $i_indice, $value['alternativa_nivel_disc']);
    $objPHPExcel->getActiveSheet()->getStyle('K' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('K' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $objPHPExcel->setActiveSheetIndex(0)->mergeCells('L' . $i_indice . ':L' . $i_indice)
                    ->setCellValue('L' . $i_indice, $value['alternativa_nivel_dific']);
    $objPHPExcel->getActiveSheet()->getStyle('L' . $i_indice)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('L' . $i_indice)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

    $i_indice++;
}

















// Redirect output to a client's web browser (Xlsx)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Pantilla Carga Pauta.Xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0


//old PhpExcel code:
//$writer = PHPExcel_IOFactory::createWriter($spreadsheet, 'Excel2007');
//$writer->save('php://output');

//new code:
$writer = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$writer->save('php://output');
exit;