<?php



/**
 * Bootstrap for PhpSpreadsheet classes.
 */

// This sucks, but we have to try to find the composer autoloader

$vendorDirPath = realpath($_SERVER["DOCUMENT_ROOT"] . '/vendor');

// var_dump($vendorDirPath);
// exit;

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Helper;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}


// Create new Spreadsheet object
$objPHPExcel = new Spreadsheet();




$objPHPExcel->getProperties()->setCreator("Desarrollos .csv")
                            ->setLastModifiedBy("Desarrollos .csv")
                            ->setTitle("Office 2007 XLSX Test Document")
                            ->setSubject("Office 2007 XLSX Test Document")
                            ->setDescription("Listado Alumnos Jornada.")
                            ->setKeywords("office 2007 openxml php")
                            ->setCategory("Test result file");

// Add some data

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:E1');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Verdana');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(17);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(18);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
// $objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(30);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:E1')
            ->setCellValue('A1', strtoupper($PruebasInformeProfesor['nombre_titulo']));
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(40);

$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFill()->getStartColor()->setRGB('0073BE');


$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),

    )
); 

$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->applyFromArray(
   array(

      'font'  => array(
          'bold'  => true,
          'color' => array('rgb' => 'FFFFFF'),
          'size'  => 16,
          'name'  => 'Calibri'
      )
   )
); 



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A2:E2')
           ->setCellValue('A2', 'Prueba  '.strtoupper($PruebasInformeProfesor['nombre_prueba']));
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A2:E2')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A2:E2')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A2:E2')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A2:E2')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A2:E2')->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),

    )
);

$objPHPExcel->getActiveSheet()->getStyle('A2:C2')->applyFromArray(
   array(

      'font'  => array(
          'bold'  => true,
          'color' => array('rgb' => 'FFFFFF'),
          'italic' => true,
          'size'  => 16,
          'name'  => 'Calibri'
      )
   )
); 



$arreglo_estilo_letras = array(

   'font'  => array(
       'bold'  => true,
       'color' => array('rgb' => 'FFFFFF'),
       'size'  => 12,
       'name'  => 'Calibri'
   )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A3:A3')
           ->setCellValue('A3', 'Cantidad de Pruebas ');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A3')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A3:A3')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);





$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B3:E3')
           ->setCellValue('B3', $PruebasInformeProfesor['cantidad_pruebas']);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(4)->setRowHeight(18);
// $objPHPExcel->getActiveSheet()->getStyle('B3:B3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('B3:B3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('B3:C3')->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'c0c0c0'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'c0c0c0'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'c0c0c0'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'c0c0c0'
            )
        ),

    )
);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A4:A4');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A4')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A4:A4')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);




$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B4:C4')
           ->setCellValue('B4', 'Puntaje Estándar');
$objPHPExcel->getActiveSheet()->getStyle('B4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B4')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B4')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B4')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('B4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('B4:C4')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D4:E4')
           ->setCellValue('D4', 'Preguntas Buenas');
$objPHPExcel->getActiveSheet()->getStyle('D4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D4')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D4')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D4')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('D4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('D4:E4')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A5:A5')
           ->setCellValue('A5', 'Maximo Posible');
$objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A5')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A5')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A5')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A5:A5')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);



$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);



$objPHPExcel->getActiveSheet()->mergeCells('B5:C5')->setCellValue('B5', $PruebasInformeProfesor['puntaje_maximo_posible']);

$objPHPExcel->getActiveSheet()->mergeCells('D5:E5')->setCellValue('D5', $PruebasInformeProfesor['preguntas_max_correctas']);




$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A6:A6')
           ->setCellValue('A6', 'Maximo Obtenido');
$objPHPExcel->getActiveSheet()->getStyle('A6')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A6')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A6')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A6')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A6')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A6')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A6:A6')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);




$objPHPExcel->getActiveSheet()->mergeCells('B6:C6')->setCellValue('B6', $PruebasInformeProfesor['puntaje_maximo']);

$objPHPExcel->getActiveSheet()->mergeCells('D6:E6')->setCellValue('D6', $PruebasInformeProfesor['preguntas_maximo']);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A7:A7')
           ->setCellValue('A7', 'Mínimo Obtenido');
$objPHPExcel->getActiveSheet()->getStyle('A7')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A7')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A7')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A7')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A7')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A7')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A7:A7')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);





$objPHPExcel->getActiveSheet()->mergeCells('B7:C7')->setCellValue('B7', $PruebasInformeProfesor['puntaje_minimo']);

$objPHPExcel->getActiveSheet()->mergeCells('D7:E7')->setCellValue('D7', $PruebasInformeProfesor['preguntas_minimo']);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A8:A8')
           ->setCellValue('A8', 'Promedio');
$objPHPExcel->getActiveSheet()->getStyle('A8')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A8')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A8')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A8')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A8')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A8:A8')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);




$objPHPExcel->getActiveSheet()->mergeCells('B8:C8')->setCellValue('B8', $PruebasInformeProfesor['promedio']);

$objPHPExcel->getActiveSheet()->mergeCells('D8:E8')->setCellValue('D8', $PruebasInformeProfesor['preguntas_promedio']);




$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A12:A12')
           ->setCellValue('A12', 'Asignatura');
$objPHPExcel->getActiveSheet()->getStyle('A12')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A12')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A12')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A12')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A12')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A12')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A12')->applyFromArray($arreglo_estilo_letras); 



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B12:B12')
           ->setCellValue('B12', 'Cantidad de Preguntas');
$objPHPExcel->getActiveSheet()->getStyle('B12')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B12')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B12')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B12')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B12')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('B12')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B12')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C12:C12')
           ->setCellValue('C12', '% Buenas');
$objPHPExcel->getActiveSheet()->getStyle('C12')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C12')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C12')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C12')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C12')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('C12')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C12')->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D12:D12')
           ->setCellValue('D12', '% Malas');
$objPHPExcel->getActiveSheet()->getStyle('D12')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D12')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D12')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D12')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D12')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('D12')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D12')->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('E12:E12')
           ->setCellValue('E12', '% Omitidas');
$objPHPExcel->getActiveSheet()->getStyle('E12')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E12')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E12')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E12')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('E12')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('E12')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('E12')->applyFromArray($arreglo_estilo_letras); 



$objPHPExcel->getActiveSheet()->getStyle('A12:E12')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A12:E12')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A12:E12')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A12:E12')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);






$objPHPExcel->getActiveSheet()->getStyle('A12:E12')->getBorders()->applyFromArray(
   array(
       'left'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'right'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'top'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),
       'button'     => array(
           'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
           'color' => array(
               'rgb' => 'FFFFFF'
           )
       ),

   )
);

$i = 13;

foreach($PruebasInformeProfesor['Ramos_array'] as $ramo){

   $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $ramo["nombre_ramo"]);
   $objPHPExcel->getActiveSheet()->setCellValue('B' . $i, $ramo["cantidad_preguntas"]);
   $objPHPExcel->getActiveSheet()->setCellValue('C' . $i, $ramo["porcentaje_buenas"]);
   $objPHPExcel->getActiveSheet()->setCellValue('D' . $i, $ramo["porcentaje_malas"]);
   $objPHPExcel->getActiveSheet()->setCellValue('E' . $i, $ramo["porcentaje_omitidas"]);

   $i++;
}


// Redirect output to a client's web browser (Xlsx)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Estadisticas_Generales_' . strtoupper($PruebasInformeProfesor['nombre_titulo']) . '_'.strtoupper($PruebasInformeProfesor['nombre_prueba']).'.Xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0


//old PhpExcel code:
//$writer = PHPExcel_IOFactory::createWriter($spreadsheet, 'Excel2007');
//$writer->save('php://output');

//new code:
$writer = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$writer->save('php://output');
exit;