<?php

use yii\helpers\ArrayHelper;

/**
 * Bootstrap for PhpSpreadsheet classes.
 */

// This sucks, but we have to try to find the composer autoloader

$vendorDirPath = realpath($_SERVER["DOCUMENT_ROOT"] . '/vendor');

// var_dump($vendorDirPath);
// exit;

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Helper;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}


// Create new Spreadsheet object
$objPHPExcel = new Spreadsheet();




$objPHPExcel->getProperties()->setCreator("Desarrollos .csv")
                            ->setLastModifiedBy("Desarrollos .csv")
                            ->setTitle("Office 2007 XLSX Test Document")
                            ->setSubject("Office 2007 XLSX Test Document")
                            ->setDescription("Listado Alumnos Jornada.")
                            ->setKeywords("office 2007 openxml php")
                            ->setCategory("Test result file");




$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:F1');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Verdana');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(17);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(18);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('AE1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(60);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(30);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:F1')
            ->setCellValue('A1', strtoupper($PruebasInformeProfesor['nombre_titulo']));
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(40);

$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
                            
 
$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
); 

$objPHPExcel->getActiveSheet()->getStyle('A1:F1')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A2:F2')
            ->setCellValue('A2', 'Prueba  '.strtoupper($PruebasInformeProfesor['nombre_prueba']));
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A2:F2')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A2:F2')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A2:F2')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A2:F2')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A2:F2')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('A2:F2')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'italic' => true,
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 

$arreglo_estilo_letras = array(

    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => 'FFFFFF'),
        'size'  => 12,
        'name'  => 'Calibri'
    )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A3:A3')
            ->setCellValue('A3', 'Asignatura');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B3:B3')
            ->setCellValue('B3', 'Porcentaje medio de respuestas correctas Eje Temático');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C3:C3')
            ->setCellValue('C3', 'Cantidad de Preguntas');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C3')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D3:D3')
            ->setCellValue('D3', '% Promedio del Grupo');
$objPHPExcel->getActiveSheet()->getStyle('D3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D3')->applyFromArray($arreglo_estilo_letras); 



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('E3:E3')
            ->setCellValue('E3', 'Nivel de Desempeño');
$objPHPExcel->getActiveSheet()->getStyle('E3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('E3')->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('F3:F3')
            ->setCellValue('F3', 'Descripción de niveles');
$objPHPExcel->getActiveSheet()->getStyle('F3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('F3')->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->getActiveSheet()->getStyle('A3:F3')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A3:F3')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A3:F3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A3:F3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);






$objPHPExcel->getActiveSheet()->getStyle('A3:F3')->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),

    )
);



$i = 4;

$ibh = $i;
$indice = 1;
$total = 0 ;

$i_base = ($i + 5);

$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i), 'Alto > 80%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 1), 'Medio Alto > 60% <= 80%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 2), 'Medio > 40% <= 60%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 3), 'Medio Bajo >= 30% <= 40%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 4), 'Bajo < 30%');



$ramos = ArrayHelper::index($PruebasInformeProfesor['Ejes'],null, 'id_ramo');

foreach($ramos as $ramo){


    foreach($ramo as $eje){
        

        $inormal = $ibh;

        $ibh_final = $ibh;

        $cantidad_coincidencias = 0;



        $objPHPExcel->getActiveSheet()->setCellValue('B' . $ibh, $eje["nombre"])->mergeCells('B' . $ibh . ':B'.$ibh_final);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->getStartColor()->setRGB('c0c0c0');
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh . ':B'.$ibh_final)->getBorders()->applyFromArray(
             array(
                 'left'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'right'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'top'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'button'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),

             )
        );

        $objPHPExcel->getActiveSheet()->setCellValue('C' . $ibh, $eje["cantidad_preguntas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('D' . $ibh, $eje["porcentaje_buenas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('E' . $ibh, $eje["calificacion_buenas"]);


        $ibh = $ibh_final + 1;

    }

    $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $ramo[0]["nombre_ramo"])->mergeCells('A' . $i . ':A'.$ibh_final);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('c0c0c0');
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



    $objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':A'.$ibh_final)->getBorders()->applyFromArray(
        array(
            'left'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'right'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'top'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'button'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),

        )
    );

   

    $i = $ibh_final + 1;
    $indice++;
}





if($i_base > $i){
    $i = ($i_base + 1);
}else{
    $i++;
}



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A' . $i . ':A' . $i)
            ->setCellValue('A' . $i, 'Asignatura');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B' . $i . ':B' . $i)
            ->setCellValue('B' . $i, 'Porcentaje medio de respuestas erradas Eje Temático');
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C' . $i . ':C' . $i)
            ->setCellValue('C' . $i, 'Cantidad de Preguntas');
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D' . $i . ':D' . $i)
            ->setCellValue('D' . $i, '% Promedio del Grupo');
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('E' . $i . ':E' . $i)
            ->setCellValue('E' . $i, 'Nivel de Desempeño');
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('F' . $i . ':F' . $i)
            ->setCellValue('F' . $i, 'Descripción de niveles');
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),

    )
);




$i++;

$ibh = $i;

$indice = 1;
$total = 0 ;

$i_base = ($i + 5);

$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i), 'Alto <= 10%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 1), 'Medio Alto > 10% <= 20%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 2), 'Medio > 20% <= 30%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 3), 'Medio Bajo > 30% <= 40%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 4), 'Bajo > 40%');


$ramos = ArrayHelper::index($PruebasInformeProfesor['Ejes'],null, 'id_ramo');

foreach($ramos as $ramo){


    foreach($ramo as $eje){
        

        $inormal = $ibh;

        $ibh_final = $ibh;

        $cantidad_coincidencias = 0;



        $objPHPExcel->getActiveSheet()->setCellValue('B' . $ibh, $eje["nombre"])->mergeCells('B' . $ibh . ':B'.$ibh_final);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->getStartColor()->setRGB('c0c0c0');
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh . ':B'.$ibh_final)->getBorders()->applyFromArray(
             array(
                 'left'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'right'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'top'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'button'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),

             )
        );

        $objPHPExcel->getActiveSheet()->setCellValue('C' . $ibh, $eje["cantidad_preguntas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('D' . $ibh, $eje["porcentaje_malas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('E' . $ibh, $eje["calificacion_malas"]);


        $ibh = $ibh_final + 1;

    }

    $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $ramo[0]["nombre_ramo"])->mergeCells('A' . $i . ':A'.$ibh_final);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('c0c0c0');
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



    $objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':A'.$ibh_final)->getBorders()->applyFromArray(
        array(
            'left'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'right'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'top'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'button'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),

        )
    );

   

    $i = $ibh_final + 1;
    $indice++;
}




if($i_base > $i){
    $i = ($i_base + 1);
}else{
    $i++;
}


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A' . $i . ':A' . $i)
            ->setCellValue('A' . $i, 'Asignatura');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B' . $i . ':B' . $i)
            ->setCellValue('B' . $i, 'Porcentaje medio de respuestas omitidas Eje Temático');
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C' . $i . ':C' . $i)
            ->setCellValue('C' . $i, 'Cantidad de Preguntas');
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C' . $i)->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('D' . $i . ':D' . $i)
            ->setCellValue('D' . $i, '% Promedio del Grupo');
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('D' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('E' . $i . ':E' . $i)
            ->setCellValue('E' . $i, 'Nivel de Desempeño');
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);


$objPHPExcel->getActiveSheet()->getStyle('E' . $i)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('F' . $i . ':F' . $i)
            ->setCellValue('F' . $i, 'Descripción de niveles');
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);


$objPHPExcel->getActiveSheet()->getStyle('F' . $i)->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':F' . $i)->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),

     )
);



$i++;

$ibh = $i;

$indice = 1;
$total = 0 ;

$i_base = ($i + 5);

$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i), 'Alto <= 10%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 1), 'Medio Alto > 10% <= 20%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 2), 'Medio > 20% <= 30%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 3), 'Medio Bajo > 30% <= 40%');
$objPHPExcel->getActiveSheet()->setCellValue('F' . ($i + 4), 'Bajo > 40%');


$ramos = ArrayHelper::index($PruebasInformeProfesor['Ejes'],null, 'id_ramo');

foreach($ramos as $ramo){


    foreach($ramo as $eje){
        

        $inormal = $ibh;

        $ibh_final = $ibh;

        $cantidad_coincidencias = 0;



        $objPHPExcel->getActiveSheet()->setCellValue('B' . $ibh, $eje["nombre"])->mergeCells('B' . $ibh . ':B'.$ibh_final);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getFill()->getStartColor()->setRGB('c0c0c0');
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
        // $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



        $objPHPExcel->getActiveSheet()->getStyle('B' . $ibh . ':B'.$ibh_final)->getBorders()->applyFromArray(
             array(
                 'left'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'right'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'top'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),
                 'button'     => array(
                     'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                     'color' => array(
                         'rgb' => 'FFFFFF'
                     )
                 ),

             )
        );

        $objPHPExcel->getActiveSheet()->setCellValue('C' . $ibh, $eje["cantidad_preguntas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('D' . $ibh, $eje["porcentaje_omitidas"]);
        $objPHPExcel->getActiveSheet()->setCellValue('E' . $ibh, $eje["calificacion_omitidas"]);


        $ibh = $ibh_final + 1;

    }

    $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $ramo[0]["nombre_ramo"])->mergeCells('A' . $i . ':A'.$ibh_final);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('c0c0c0');
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



    $objPHPExcel->getActiveSheet()->getStyle('A' . $i . ':A'.$ibh_final)->getBorders()->applyFromArray(
        array(
            'left'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'right'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'top'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),
            'button'     => array(
                'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                'color' => array(
                    'rgb' => 'FFFFFF'
                )
            ),

        )
    );

   

    $i = $ibh_final + 1;
    $indice++;
}

// foreach($PruebasInformeProfesor['Ejes'] as $eje){

//     $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $eje["nombre"]);
//     $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
//     $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('c0c0c0');
//     // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
//     // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



//     $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->applyFromArray(
//          array(
//              'left'     => array(
//                  'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//                  'color' => array(
//                      'rgb' => 'c0c0c0'
//                  )
//              ),
//              'right'     => array(
//                  'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//                  'color' => array(
//                      'rgb' => 'c0c0c0'
//                  )
//              ),
//              'top'     => array(
//                  'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//                  'color' => array(
//                      'rgb' => 'c0c0c0'
//                  )
//              ),
//              'button'     => array(
//                  'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//                  'color' => array(
//                      'rgb' => 'c0c0c0'
//                  )
//              ),

//          )
//     );

    
//     $objPHPExcel->getActiveSheet()->setCellValue('B' . $i, $eje["cantidad_preguntas"]);
//     $objPHPExcel->getActiveSheet()->setCellValue('C' . $i, $eje["porcentaje_omitidas"]);
//     $objPHPExcel->getActiveSheet()->setCellValue('D' . $i, $eje["calificacion_omitidas"]);

   

//     $i++;
//     $indice++;
// }









// Redirect output to a client's web browser (Xlsx)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Resultados_por_eje_temático_'.strtoupper($PruebasInformeProfesor['nombre_titulo']).'_'.strtoupper($PruebasInformeProfesor['nombre_prueba']).'.Xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0


//old PhpExcel code:
//$writer = PHPExcel_IOFactory::createWriter($spreadsheet, 'Excel2007');
//$writer->save('php://output');

//new code:
$writer = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$writer->save('php://output');
exit;
