<?php



/**
 * Bootstrap for PhpSpreadsheet classes.
 */

// This sucks, but we have to try to find the composer autoloader

$vendorDirPath = realpath($_SERVER["DOCUMENT_ROOT"] . '/vendor');

// var_dump($vendorDirPath);
// exit;

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Helper;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}


// Create new Spreadsheet object
$objPHPExcel = new Spreadsheet();




$objPHPExcel->getProperties()->setCreator("Desarrollos .csv")
                            ->setLastModifiedBy("Desarrollos .csv")
                            ->setTitle("Office 2007 XLSX Test Document")
                            ->setSubject("Office 2007 XLSX Test Document")
                            ->setDescription("Listado Alumnos Jornada.")
                            ->setKeywords("office 2007 openxml php")
                            ->setCategory("Test result file");



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:C1');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Verdana');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(17);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(18);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('AC1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:J1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A1:J1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(10);







$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:C1')
            ->setCellValue('A1', strtoupper($PruebasInformeProfesor['nombre_titulo']));
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(40);

$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AC1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
                            
 
$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
); 

$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A2:C2')
            ->setCellValue('A2', 'Prueba  '.strtoupper($PruebasInformeProfesor['nombre_prueba']));
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AC1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A2:C2')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A2:C2')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A2:C2')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A2:C2')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A2:C2')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('A2:C2')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'italic' => true,
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$arreglo_estilo_letras = array(

    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => 'FFFFFF'),
        'size'  => 12,
        'name'  => 'Calibri'
    )
);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A3:A3')
            ->setCellValue('A3', 'Tramo');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray($arreglo_estilo_letras); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B3:B3')
            ->setCellValue('B3', 'N° de Alumnos');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('C3:C3')
            ->setCellValue('C3', 'Porcentaje');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('C3')->applyFromArray($arreglo_estilo_letras); 



$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('C5:C18')
->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);

$linea = 4;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 800 y 850');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_ocho_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_ocho_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_ocho_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 750 y 799');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_siete_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_siete_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_siete_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 700 y 749');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_siete_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_siete_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_siete_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 650 y 699');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_seis_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_seis_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_seis_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 600 y 649');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_seis_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_seis_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_seis_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 550 y 599');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_cinco_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_cinco_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_cinco_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 500 y 549');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_cinco_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_cinco_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_cinco_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 450 y 499');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_cuatro_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_cuatro_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_cuatro_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 400 y 449');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_cuatro_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_cuatro_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_cuatro_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 350 y 399');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_tres_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_tres_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_tres_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 300 y 349');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_tres_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_tres_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_tres_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 250 y 299');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_dos_dos']);

if ($PruebasInformeProfesor['tramos']['tramo_dos_dos'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_dos_dos'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 200 y 249');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_dos_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_dos_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_dos_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");




$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Entre 0 y 199');

$objPHPExcel->getActiveSheet()->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['tramo_uno']);

if ($PruebasInformeProfesor['tramos']['tramo_uno'] == 0) {
    $porcentaje = "0";
}else{
    $porcentaje = ($PruebasInformeProfesor['tramos']['tramo_uno'] * 100);

    $porcentaje = round(($porcentaje / $PruebasInformeProfesor['tramos']['cantidad_pruebas']),0);
}

$objPHPExcel->getActiveSheet()->setCellValue('C' . $linea, $porcentaje . "%");






$linea++;

$objPHPExcel->getActiveSheet()->setCellValue('A' . $linea, 'Total de Alumnos');

$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->applyFromArray($arreglo_estilo_letras); 

$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('A' . $linea)->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),

     )
);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B' . $linea.':C' . $linea)
            ->setCellValue('B' . $linea, $PruebasInformeProfesor['tramos']['cantidad_pruebas']);
$objPHPExcel->getActiveSheet()->getStyle('B' . $linea)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $linea)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B' . $linea)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B' . $linea)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B' . $linea)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(4)->setRowHeight(18);
// $objPHPExcel->getActiveSheet()->getStyle('B3:B' . $linea)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('B3:B' . $linea)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('B' . $linea.':C' . $linea)->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),

     )
);





                                        
                                        
                                        




















// Redirect output to a client's web browser (Xlsx)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Resultados_por_tramo_'.strtoupper($PruebasInformeProfesor['nombre_titulo']).'_'.strtoupper($PruebasInformeProfesor['nombre_prueba']).'.Xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0


//old PhpExcel code:
//$writer = PHPExcel_IOFactory::createWriter($spreadsheet, 'Excel2007');
//$writer->save('php://output');

//new code:
$writer = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$writer->save('php://output');
exit;