<?php



/**
 * Bootstrap for PhpSpreadsheet classes.
 */

// This sucks, but we have to try to find the composer autoloader

$vendorDirPath = realpath($_SERVER["DOCUMENT_ROOT"] . '/vendor');

// var_dump($vendorDirPath);
// exit;

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Helper;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}


// Create new Spreadsheet object
$objPHPExcel = new Spreadsheet();




$objPHPExcel->getProperties()->setCreator("Desarrollos .csv")
                            ->setLastModifiedBy("Desarrollos .csv")
                            ->setTitle("Office 2007 XLSX Test Document")
                            ->setSubject("Office 2007 XLSX Test Document")
                            ->setDescription("Listado Alumnos Jornada.")
                            ->setKeywords("office 2007 openxml php")
                            ->setCategory("Test result file");


$Ejes = ArrayHelper::index($PruebasInformeProfesor['Ejes'],null, 'eje_tematico');

$arr = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL','AM','AN','AO','AP','AQ','AR','AS','AT','AU','AV','AW','AX','AY','AZ'); 

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:'.$arr[(count($Ejes) + 1)].'1');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Verdana');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(17);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(18);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(30);

$objPHPExcel->getActiveSheet()->getColumnDimension($arr[(count($Ejes) + 1)])->setWidth(30);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A1:'.$arr[(count($Ejes) + 1)].'1')
            ->setCellValue('A1', strtoupper($PruebasInformeProfesor['nombre_titulo']));
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(40);

$objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);
                            
 
$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
); 

$objPHPExcel->getActiveSheet()->getStyle('A1:'.$arr[(count($Ejes) + 1)].'1')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A2:'.$arr[(count($Ejes) + 1)].'2')
            ->setCellValue('A2', 'Prueba  '.strtoupper($PruebasInformeProfesor['nombre_prueba']));
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('A2:'.$arr[(count($Ejes) + 1)].'2')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'italic' => true,
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$arreglo_estilo_letras = array(

    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => 'FFFFFF'),
        'size'  => 12,
        'name'  => 'Calibri'
    )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('B3:'.$arr[(count($Ejes) + 1)].'3')
            ->setCellValue('B3', 'EJE TEMÄTICO');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setSize(16);
$objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('AI1')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
$objPHPExcel->getActiveSheet()->getStyle('A3:'.$arr[(count($Ejes) + 1)].'3')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A3:'.$arr[(count($Ejes) + 1)].'3')->getFill()->getStartColor()->setRGB('0073BE');
// $objPHPExcel->getActiveSheet()->getStyle('B3:'.$arr[(count($Ejes) + 1)].'3')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('B3:'.$arr[(count($Ejes) + 1)].'3')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('B3:'.$arr[(count($Ejes) + 1)].'3')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->getActiveSheet()->getStyle('B3:'.$arr[(count($Ejes) + 1)].'3')->applyFromArray(
    array(

       'font'  => array(
           'bold'  => true,
           'color' => array('rgb' => 'FFFFFF'),
           'italic' => true,
           'size'  => 16,
           'name'  => 'Calibri'
       )
    )
); 


$arreglo_estilo_letras = array(

    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => 'FFFFFF'),
        'size'  => 12,
        'name'  => 'Calibri'
    )
);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A4:A4')
->setCellValue('A4', 'Ramos');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension(4)->setRowHeight(40);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A4')->applyFromArray($arreglo_estilo_letras);         
                                        
$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[(count($Ejes) + 1)].'4')->getBorders()->applyFromArray(
    array(
        'left'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'right'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'top'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),
        'button'     => array(
            'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
            'color' => array(
                'rgb' => 'FFFFFF'
            )
        ),

    )
);

$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[(count($Ejes) + 1)].'4')->applyFromArray(
   array(

      'font'  => array(
          'bold'  => true,
          'color' => array('rgb' => 'FFFFFF'),
          'italic' => true,
          'size'  => 16,
          'name'  => 'Calibri'
      )
   )
); 

$objPHPExcel->getActiveSheet()->getStyle('A4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A4')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A4')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);





$ramos = ArrayHelper::index($PruebasInformeProfesor['Ejes'],null, 'id_ramo');

$arreglo_ejes = [];
$iRamo = 1;
$iEje = 1;
foreach ($ramos as $key => $ramo) {



    $Ejes_ramo = ArrayHelper::index($ramo,null, 'eje_tematico');

    
    foreach ($Ejes_ramo as $key => $eje) {
    
    
        $arreglo_ejes[] = $eje[0]["eje_tematico"];
        
        $objPHPExcel->setActiveSheetIndex(0)->mergeCells($arr[($iEje)].'5:'.$arr[($iEje)].'5')
                    ->setCellValue($arr[($iEje)].'5', $eje[0]["nombre_eje_tematico"]);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setName('Calibri');
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setSize(12);
        $objPHPExcel->getActiveSheet()->getRowDimension(5)->setRowHeight(33);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
    
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->applyFromArray($arreglo_estilo_letras);
    
        $iEje++;
    }



    $objPHPExcel->setActiveSheetIndex(0)->mergeCells($arr[($iRamo)].'4:'.$arr[($iEje - 1)].'4')
                ->setCellValue($arr[($iRamo)].'4', $ramo[0]["nombre_ramo"]);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getFont()->setBold(true);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getFont()->setName('Calibri');
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getFont()->setSize(12);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

    $objPHPExcel->getActiveSheet()->getStyle($arr[($iRamo)].'4')->applyFromArray($arreglo_estilo_letras);

    $iRamo = $iEje;
    
}

$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[($iRamo - 1)].'4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[($iRamo - 1)].'4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[($iRamo - 1)].'4')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A4:'.$arr[($iRamo - 1)].'4')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);





$objPHPExcel->getActiveSheet()->getStyle('A5:'.$arr[(count($Ejes) + 1)].'5')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A5:'.$arr[(count($Ejes) + 1)].'5')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle('A5:'.$arr[(count($Ejes) + 1)].'5')->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
$objPHPExcel->getActiveSheet()->getStyle('A5:'.$arr[(count($Ejes) + 1)].'5')->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->setActiveSheetIndex(0)->mergeCells($arr[($iEje)].'4:'.$arr[($iEje)].'4');
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFill()->getStartColor()->setRGB('005085');
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->applyFromArray($arreglo_estilo_letras);



$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'4')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);


$objPHPExcel->setActiveSheetIndex(0)->mergeCells($arr[($iEje)].'5:'.$arr[($iEje)].'5')
            ->setCellValue($arr[($iEje)].'5', 'Total por Habilidad');
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->setSize(12);

$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)].'5')->applyFromArray($arreglo_estilo_letras);


$objPHPExcel->getActiveSheet()->getStyle('A5:'.$arr[(count($Ejes) + 1)].'5')->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFFFFF'
             )
         ),

     )
);

$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A5:A5')
            ->setCellValue('A5', 'Total por Habilidad');
$objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A5')->applyFromArray($arreglo_estilo_letras);






$i = 6;

$cuenta_totales = [];

foreach ($PruebasInformeProfesor['Habilidades'] as $key => $Habilidad) {

    $total_preguntas_habilidad = 0;

    $Habilidad_id = $Habilidad[0]["habilidad_id"];


    $objPHPExcel->getActiveSheet()->setCellValue('A' . $i, $Habilidad[0]["nombre_habilidad"]);

    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('005085');
    $objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
    // $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->applyFromArray($arreglo_estilo_letras);

    $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->applyFromArray(
         array(
             'left'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'FFFFFF'
                 )
             ),
             'right'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'FFFFFF'
                 )
             ),
             'top'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'FFFFFF'
                 )
             ),
             'button'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'FFFFFF'
                 )
             ),

         )
    );


    $iEje = 1;

    foreach ($arreglo_ejes as $key => $arreglo_eje) {

        $cantidad_preguntas_eje_habilidad = 0;
        $preguntas = "";

        foreach ($Ejes[$arreglo_eje] as $key => $value) {

            if ($Habilidad_id == $value["habilidad_id"]) {
                if ($preguntas == "") {
                    $preguntas .= $value["numero_pregunta"];

                }else{
                    $preguntas .= "-" . $value["numero_pregunta"];
                }

                $cantidad_preguntas_eje_habilidad++;

                $total_preguntas_habilidad++;
            }
            
        }


        if(!ArrayHelper::keyExists(($iEje - 1), $cuenta_totales , false)){

            $cuenta_totales[] = $cantidad_preguntas_eje_habilidad;
            
        }else{
            $cuenta_totales[($iEje - 1)] += $cantidad_preguntas_eje_habilidad;
        }


        $objPHPExcel->getActiveSheet()->setCellValue($arr[($iEje)] . $i, $preguntas);
        $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);





        $iEje++;


    }


    

    $objPHPExcel->getActiveSheet()->setCellValue($arr[($iEje)] . $i, $total_preguntas_habilidad);

    $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getFill()->getStartColor()->setRGB('c0c0c0');
    $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    // $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
    // $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



    $objPHPExcel->getActiveSheet()->getStyle($arr[($iEje)] . $iEje)->getBorders()->applyFromArray(
         array(
             'left'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'c0c0c0'
                 )
             ),
             'right'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'c0c0c0'
                 )
             ),
             'top'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'c0c0c0'
                 )
             ),
             'button'     => array(
                 'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                 'color' => array(
                     'rgb' => 'c0c0c0'
                 )
             ),

         )
    );

    if(!ArrayHelper::keyExists(($iEje - 1), $cuenta_totales , false)){

        $cuenta_totales[] = $total_preguntas_habilidad;
        
    }else{
        $cuenta_totales[($iEje - 1)] += $total_preguntas_habilidad;
    }

    $i++;

}




$objPHPExcel->setActiveSheetIndex(0)->mergeCells('A' . $i.':A' . $i)
            ->setCellValue('A' . $i, 'Total');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setName('Calibri');
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getRowDimension($i)->setRowHeight(33);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);

$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getFill()->getStartColor()->setRGB('005085');

$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->applyFromArray($arreglo_estilo_letras);

// $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('A' . $i)->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'FFCC00'
             )
         ),

     )
);


foreach ($cuenta_totales as $key => $totales) {
    $objPHPExcel->setActiveSheetIndex(0)->mergeCells($arr[($key + 1)] . $i.':'.$arr[($key + 1)] . $i)
                ->setCellValue($arr[($key + 1)] . $i, $totales);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)])->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getFont()->setBold(true);
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getFont()->setName('Calibri');
    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getFont()->setSize(12);

    $objPHPExcel->getActiveSheet()->getStyle($arr[($key + 1)] . $i)->getFont()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK);
}



$objPHPExcel->getActiveSheet()->getStyle('B'. $i .':'.$arr[(count($Ejes) + 1)].$i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('B'. $i .':'.$arr[(count($Ejes) + 1)].$i)->getFill()->getStartColor()->setRGB('c0c0c0');
// $objPHPExcel->getActiveSheet()->getStyle('B'. $i .':'.$arr[(count($Ejes) + 1)].$i)->getBorders()->getBottom()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK);
// $objPHPExcel->getActiveSheet()->getStyle('B'. $i .':'.$arr[(count($Ejes) + 1)].$i)->getBorders()->getBottom()->getColor()->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);



$objPHPExcel->getActiveSheet()->getStyle('B'. $i .':'.$arr[(count($Ejes) + 1)].$iEje)->getBorders()->applyFromArray(
     array(
         'left'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'right'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'top'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),
         'button'     => array(
             'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
             'color' => array(
                 'rgb' => 'c0c0c0'
             )
         ),

     )
);





// Redirect output to a client's web browser (Xlsx)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Tabla_especificaciones_'.$PruebasInformeProfesor['nombre_titulo'].'_'.strtoupper($PruebasInformeProfesor['nombre_prueba']).'.Xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0


//old PhpExcel code:
//$writer = PHPExcel_IOFactory::createWriter($spreadsheet, 'Excel2007');
//$writer->save('php://output');

//new code:
$writer = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$writer->save('php://output');
exit;